name: hello-world
services:
  api:
    build:
      context: .
    interfaces:
      main:
        ingress:
          subdomain: hello
          # ip_whitelist:
          #   - ${{ secrets.test_ip }}
          #   - 8.8.8.8
          #   - 8.8.4.4
          # ip_whitelist: ${{ secrets.test_ip }}
          ip_whitelist: 
            - 108.26.152.50
        port: 3000

secrets:
  test_ip:
    required: false
#     required: true
