version: 2.1

jobs:
  create-preview:
    docker:
      - image: cimg/node:18.14.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
          # docker_layer_caching: true
      - run:
          name: Install Archiect CLI
          command: npm install -g @architect-io/cli
      - run:
          name: Log in to Architect
          command: architect login # environment variables are set in the UI
      - run:
          name: Create environment
          command: architect environment:create $CIRCLE_BRANCH --cluster architect # TODO: set cluster as a project var
      - run:
          name: Deploy component
          command: architect deploy architect.yml --auto-approve -e $CIRCLE_BRANCH

workflows:
  preview-workflow:
    jobs: # TODO: consider adding Docker Layer Caching
      - create-preview
