version: 2.1

parameters: # TODO: clean up?
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

jobs:
  create-preview:
    docker:
      - image: cimg/node:18.14.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
          # docker_layer_caching: true
      - run: # TODO: uncomment
          name: Install Architect CLI
          command: npm install -g @architect-io/cli
      - run:
          name: Log in to Architect
          command: architect login # environment variables are set in the UI
      - run:
          name: Set $PR_NUMBER environment variable for job
          command: |
            export PR_NUMBER=$(echo $CIRCLE_BRANCH | sed 's/[^0-9]*//g')
            echo 'export PR_NUMBER=$PR_NUMBER' >> "$BASH_ENV"
      - run: # TODO: set cluster as a project var
          name: Create environment
          command: architect environment:create preview-$PR_NUMBER --cluster architect --ttl=1d
      - run:
          name: Deploy component
          command: architect deploy architect.yml --auto-approve -e preview-$PR_NUMBER
  destroy-preview:
    docker:
      - image: cimg/node:18.14.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
          # docker_layer_caching: true
      - run:
          name: Install Architect CLI
          command: npm install -g @architect-io/cli
      - run:
          name: Log in to Architect
          command: architect login # environment variables are set in the UI
      - run:
          name: Set $PR_NUMBER environment variable for job
          command: |
            export PR_NUMBER=$(echo $CIRCLE_BRANCH | sed 's/[^0-9]*//g')
            echo 'export PR_NUMBER=$PR_NUMBER' >> "$BASH_ENV"
      - run:
          name: Destroy component
          command: architect destroy --environment preview-$PR_NUMBER --auto-approve
      - run:
          name: Destroy environment
          command: architect environment:destroy preview-$PR_NUMBER --auto-approve

workflows:
  create-preview-workflow:
    when:
      equal: [ open, << pipeline.parameters.GHA_Meta >>]
    jobs: # TODO: consider adding Docker Layer Caching
      - create-preview
  destroy-preview-workflow:
    when:
      equal: [ closed, << pipeline.parameters.GHA_Meta >>]
    jobs: # TODO: consider adding Docker Layer Caching
      - destroy-preview
