version: 2.1

jobs:
  create-preview:
    docker:
      - image: cimg/node:18.14.1
    steps:
      - checkout
      - run:
          name: Install Archiect CLI
          command: npm install -g @architect-io/cli
      - run:
          name: Log in to Architect
          command: architect login # environment variables are set in the UI
      - run:
          name: Register component
          command: architect register architect.yml

workflows:
  preview-workflow:
    jobs: # TODO: consider adding Docker Layer Caching
      - create-preview
