version: 2.1

parameters: # TODO: clean up?
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

# .job_common: &job_common


jobs:
  create-preview:
    # <<: *job_common
    docker:
      - image: cimg/node:18.14.1
    steps:
      - checkout
      - run: echo << pipeline.parameters.GHA_Meta >> # TODO: remove
  #     - setup_remote_docker:
  #         version: 20.10.18
  #         # docker_layer_caching: true
  #     - run: # TODO: uncomment
  #         name: Install Architect CLI
  #         command: npm install -g @architect-io/cli
  #     - run:
  #         name: Log in to Architect
  #         command: architect login # environment variables are set in the UI
  #     - run: # TODO: set cluster as a project var
  #         name: Create environment
  #         command: architect environment:create $CIRCLE_BRANCH --cluster architect --ttl=1d
  #     - run:
  #         name: Deploy component
  #         command: architect deploy architect.yml --auto-approve -e $CIRCLE_BRANCH
  destroy-preview:
    # <<: *job_common
    docker:
      - image: cimg/node:18.14.1
    steps:
      - checkout
      - run: echo << pipeline.parameters.GHA_Meta >> # TODO: remove
      # - setup_remote_docker:
      #     version: 20.10.18
      #     # docker_layer_caching: true
      # - run:
      #     name: Install Architect CLI
      #     command: npm install -g @architect-io/cli
      # - run:
      #     name: Log in to Architect
      #     command: architect login # environment variables are set in the UI
      # - run:
      #     name: Destroy component
      #     command: architect destroy --environment << pipeline.parameters.GHA_Meta >> --auto-approve
      # - run:
      #     name: Destroy environment
      #     command: architect environment:destroy << pipeline.parameters.GHA_Meta >> --auto-approve

workflows:
  create-preview-workflow:
    when:
      equal: [ ARC_CREATE_PREVIEW, << pipeline.parameters.GHA_Meta >>]
    jobs: # TODO: consider adding Docker Layer Caching
      - create-preview
  destroy-preview-workflow:
    when:
      and:
        - not:
            equal: [ ARC_CREATE_PREVIEW, << pipeline.parameters.GHA_Meta >>]
        - << pipeline.parameters.GHA_Action >>
      # and: << pipeline.parameters.GHA_Action >>
    jobs: # TODO: consider adding Docker Layer Caching
      - destroy-preview
