version: 2.1

parameters: # TODO: clean up?
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

jobs:
  create-preview:
    docker:
      - image: cimg/node:18.14.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
          # docker_layer_caching: true
      - run: # TODO: uncomment
          name: Install Archiect CLI
          command: npm install -g @architect-io/cli
      - run:
          name: Log in to Architect
          command: architect login # environment variables are set in the UI
      - run:
          name: Create environment
          command: architect environment:create $CIRCLE_BRANCH --cluster architect # TODO: set cluster as a project var
      - run:
          name: Deploy component
          command: architect deploy architect.yml --auto-approve -e $CIRCLE_BRANCH
  destroy-preview:
    docker:
      - image: cimg/node:18.14.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
          # docker_layer_caching: true
      - run:
          name: Install Archiect CLI
          command: npm install -g @architect-io/cli
      - run:
          name: Log in to Architect
          command: architect login # environment variables are set in the UI
      # TODO: delete things

workflows:
  create-preview-workflow:
    # when: << pipeline.parameters.GHA_Action >> # TODO: uncomment to avoid circleci workflow running on all pushes
    # when:
      # equal: [ open, << pipeline.parameters.GHA_Meta >>]
      # equal: [ "pull_request", << pipeline.parameters.GHA_Event >>]
    jobs: # TODO: consider adding Docker Layer Caching
      - create-preview
  destroy-preview-workflow:
    # when: << pipeline.parameters.GHA_Action >> # TODO: uncomment to avoid circleci workflow running on all pushes
    # when:
      # equal: [ closed, << pipeline.parameters.GHA_Meta >>]
      # equal: [ "pull_request", << pipeline.parameters.GHA_Event >>]
    jobs: # TODO: consider adding Docker Layer Caching
      - destroy-preview
