name: Preview environment create trigger

on:
  pull_request:
    branches:
      - master # TODO: change to main

jobs:
  architect_create_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI Pipeline
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }} # needs to be set in github actions variables
        # with:
        #   GHA_Meta: open
